services:
  app:
    build: .
    ports:
      - '80:8080'
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: labs
      POSTGRES_PASSWORD: myverysecureandprivatepassforlabs
      POSTGRES_DB: labs
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/pgsql/data'

volumes:
  postgres:
